apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  contatiners:
    - name: client
      image: kumarvdocker/multimoduledocker-client
      ports:
        - containerPort: 3000